// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: lists/events.proto

package lists

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListPK []byte `protobuf:"bytes,1,opt,name=ListPK,proto3" json:"ListPK,omitempty"`
}

func (x *ListDeleted) Reset() {
	*x = ListDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeleted) ProtoMessage() {}

func (x *ListDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_lists_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeleted.ProtoReflect.Descriptor instead.
func (*ListDeleted) Descriptor() ([]byte, []int) {
	return file_lists_events_proto_rawDescGZIP(), []int{0}
}

func (x *ListDeleted) GetListPK() []byte {
	if x != nil {
		return x.ListPK
	}
	return nil
}

type SubscriberForgotten struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberPK   []byte `protobuf:"bytes,1,opt,name=SubscriberPK,proto3" json:"SubscriberPK,omitempty"`
	OrganizationPK []byte `protobuf:"bytes,2,opt,name=OrganizationPK,proto3" json:"OrganizationPK,omitempty"`
}

func (x *SubscriberForgotten) Reset() {
	*x = SubscriberForgotten{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriberForgotten) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberForgotten) ProtoMessage() {}

func (x *SubscriberForgotten) ProtoReflect() protoreflect.Message {
	mi := &file_lists_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberForgotten.ProtoReflect.Descriptor instead.
func (*SubscriberForgotten) Descriptor() ([]byte, []int) {
	return file_lists_events_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriberForgotten) GetSubscriberPK() []byte {
	if x != nil {
		return x.SubscriberPK
	}
	return nil
}

func (x *SubscriberForgotten) GetOrganizationPK() []byte {
	if x != nil {
		return x.OrganizationPK
	}
	return nil
}

type SubscriberOptedIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberPK []byte `protobuf:"bytes,1,opt,name=SubscriberPK,proto3" json:"SubscriberPK,omitempty"`
	ListPK       []byte `protobuf:"bytes,2,opt,name=ListPK,proto3" json:"ListPK,omitempty"`
}

func (x *SubscriberOptedIn) Reset() {
	*x = SubscriberOptedIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriberOptedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberOptedIn) ProtoMessage() {}

func (x *SubscriberOptedIn) ProtoReflect() protoreflect.Message {
	mi := &file_lists_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberOptedIn.ProtoReflect.Descriptor instead.
func (*SubscriberOptedIn) Descriptor() ([]byte, []int) {
	return file_lists_events_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriberOptedIn) GetSubscriberPK() []byte {
	if x != nil {
		return x.SubscriberPK
	}
	return nil
}

func (x *SubscriberOptedIn) GetListPK() []byte {
	if x != nil {
		return x.ListPK
	}
	return nil
}

type SubscriberOptedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberPK []byte `protobuf:"bytes,1,opt,name=SubscriberPK,proto3" json:"SubscriberPK,omitempty"`
	ListPK       []byte `protobuf:"bytes,2,opt,name=ListPK,proto3" json:"ListPK,omitempty"`
}

func (x *SubscriberOptedOut) Reset() {
	*x = SubscriberOptedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriberOptedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberOptedOut) ProtoMessage() {}

func (x *SubscriberOptedOut) ProtoReflect() protoreflect.Message {
	mi := &file_lists_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberOptedOut.ProtoReflect.Descriptor instead.
func (*SubscriberOptedOut) Descriptor() ([]byte, []int) {
	return file_lists_events_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriberOptedOut) GetSubscriberPK() []byte {
	if x != nil {
		return x.SubscriberPK
	}
	return nil
}

func (x *SubscriberOptedOut) GetListPK() []byte {
	if x != nil {
		return x.ListPK
	}
	return nil
}

var File_lists_events_proto protoreflect.FileDescriptor

var file_lists_events_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x25, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x4b, 0x22, 0x61, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x72, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x50, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x50, 0x4b, 0x12, 0x26,
	0x0a, 0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x4b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x4b, 0x22, 0x4f, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x50, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x50, 0x4b, 0x12,
	0x16, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x4b, 0x22, 0x50, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x50, 0x4b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x50,
	0x4b, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x4b, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x6e, 0x61, 0x72, 0x74, 0x6f, 0x64,
	0x65, 0x73, 0x6b, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2d, 0x64, 0x65, 0x73, 0x69, 0x67,
	0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lists_events_proto_rawDescOnce sync.Once
	file_lists_events_proto_rawDescData = file_lists_events_proto_rawDesc
)

func file_lists_events_proto_rawDescGZIP() []byte {
	file_lists_events_proto_rawDescOnce.Do(func() {
		file_lists_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_lists_events_proto_rawDescData)
	})
	return file_lists_events_proto_rawDescData
}

var file_lists_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lists_events_proto_goTypes = []interface{}{
	(*ListDeleted)(nil),         // 0: domain.events.lists.v1.ListDeleted
	(*SubscriberForgotten)(nil), // 1: domain.events.lists.v1.SubscriberForgotten
	(*SubscriberOptedIn)(nil),   // 2: domain.events.lists.v1.SubscriberOptedIn
	(*SubscriberOptedOut)(nil),  // 3: domain.events.lists.v1.SubscriberOptedOut
}
var file_lists_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lists_events_proto_init() }
func file_lists_events_proto_init() {
	if File_lists_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lists_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriberForgotten); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriberOptedIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriberOptedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lists_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lists_events_proto_goTypes,
		DependencyIndexes: file_lists_events_proto_depIdxs,
		MessageInfos:      file_lists_events_proto_msgTypes,
	}.Build()
	File_lists_events_proto = out.File
	file_lists_events_proto_rawDesc = nil
	file_lists_events_proto_goTypes = nil
	file_lists_events_proto_depIdxs = nil
}
